version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
streamsreflowing = true
farmersdelight = true
createpropulsion = true
createtransmission = true
extra_gauges = true
simulatedcoasters = true
numismatics = true
sable_player_ragdoll = true
copycats = true
create_simulated_additions = true
createdieselgenerators = true
create_submarine = true
create_enchantment_industry = true
railways = true
trmt = true
compactflap = true
createcobblestone = true
mynethersdelight = true
hotstuff = true
moonlight = true
ccredstonelinkbridge = true
sophisticatedbackpacks = true
create_radar = true
toms_peripherals = true
electroenergetics = true
create_tweaked_controllers = true
offroad = true
naturalist = true
drivebysable = true
endersdelight = true
burnt = true
cccbridge = true
createbigcannons = true
absolute_kinematics = true
ldlib2 = true
create = true
aeronautics = true
createcasing = true
simulated = true
simulatedextra = true
cbc_compact_mount = true
advancedperipherals = true
minecraft = true
lootr = true
create_dragons_plus = true
synaxis = true
create_connected = true
createdeco = true
create_potioneering = true
create_jetpack = true
trading_floor = true
powergrid = true
sable_schematic_api = true
sliceanddice = true
computercraft = true
analogaudio = true
tracks = true
aeroworks = true
